/*
* generated by Xtext
*/
package de.hoesch.erwin.xtext.sample.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SampleDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
