/*
* generated by Xtext
*/
package de.hoesch.erwin.xtext.sample.ui.contentassist;

import de.hoesch.erwin.xtext.sample.ui.contentassist.AbstractSampleDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class SampleDslProposalProvider extends AbstractSampleDslProposalProvider {

}
