/*
 * generated by Xtext
 */
package de.hoesch.erwin.xtext.sample;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SampleDslRuntimeModule extends de.hoesch.erwin.xtext.sample.AbstractSampleDslRuntimeModule {

}
