/*
 * generated by Xtext
 */
package de.hoesch.erwin.xtext.sample.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SampleDslUiModule extends de.hoesch.erwin.xtext.sample.ui.AbstractSampleDslUiModule {
	public SampleDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
